apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    tier: app
    name: catalogue
    env: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      name: catalogue
      env: testing
  template:
    metadata:
      labels:
        tier: app
        name: catalogue
        env: testing
    spec:
      containers:
        - name: catalogue
          image: rajakuma/catalogue:k1
          envFrom:
            - configMapRef:
                name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: catalogue
spec:  
  selector:
    tier: app
    name: catalogue
    env: testing
  ports:
    - name: catalogue-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"


