apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    env: testing
    type: app
spec:
  containers:
    - name: nginx-lb
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    env: testing
    type: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


