apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      app: mongo
  template:
    metadata:
      labels:
        tier: db
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: raja
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Raja@123
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          emptyDir: {}