apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    tier: db
    name: mongodb
    env: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      name: mongodb
      env: testing
  template:
    metadata:
      labels:
        tier: db
        name: mongodb
        env: testing
    spec:
      containers:
        - name: mondodb
          image: rajakuma/mongodb:k1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    tier: db
    name: mongodb
    env: testing
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017 

    